# Generated by Django 3.2.16 on 2023-07-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230717_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_code_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
